version: "3"
services:
    db:
        container_name: wardb
        image: mysql:5.7
#        ports:
#            - "3201:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: warapp
        links:
            - "db"
        build:
            context: ./
            args:
                username: root
                password: root
        ports:
            - "5000:5000"